services:
  app:
    build: .
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    env_file:
      - .env
    environment:
      - CLIENT_URL=${CLIENT_URL:-http://localhost:3001}
      - SERVER_URL=${SERVER_URL:-http://localhost:3001}
